quotes = [
"Today you are you! That is truer than true! There is no one alive who is you-er than you!",
"Don't cry because it's over. Smile because it happened.",
"You have brains in your head. You have feet in your shoes. You can steer yourself in any direction you choose. You're on your own, and you know what you know. And you are the guy who'll decide where to go.",
"The more that you read, the more things you will know. The more that you learn, the more places you'll go. ",
"I like nonsense; it wakes up the brain cells.",
"Step with care and great tact, and remember that Life's a Great Balancing Act.",
"How did it get so late so soon? Its night before its afternoon. December is here before its June. My goodness how the time has flewn. How did it get so late so soon?",
"Think left and think right and think low and think high. Oh, the thinks you can think up if only you try!",
"A person's a person, no matter how small.",
"You can get help from teachers, but you are going to have to learn a lot by yourself, sitting alone in a room.",
"Unless someone like you cares a whole awful lot, nothing is going to get better. It's not.",
"You're never too old, too wacky, too wild, to pick up a book and read to a child.",
"Today was good. Today was fun. Tomorrow is another one.",
"I meant what I said and I said what I meant.", 
"You're in pretty good shape for the shape you are in.",
"Only you can control your future.",
"I am not a consecutive writer.",
"Maybe Christmas, the Grinch thought, doesn't come from a store.",
"Preachers in pulpits talked about what a great message is in the book. No matter what you do, somebody always imputes meaning into your books.", 
"Sometimes, when I see my granddaughters make small discoveries of their own, I wish I were a child.",
"Adults are obsolete children.",
"Whenever things go a bit sour in a job I'm doing, I always tell myself, 'You can do better than this.'",
"From there to here, and here to there, funny things are everywhere.",
"I stay out of politics because if I begin thinking too much about politics, I'll probably... drop writing children's books and become a political cartoonist again.",
"I was saving the name of 'Geisel' for the Great American Novel.",
"You make 'em, I amuse 'em."
]